# Generated by Django 4.1.6 on 2023-02-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_customer_mobile"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="view_count",),
    ]
