# Generated by Django 4.1.6 on 2023-02-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_product_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="mobile",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
