# Generated by Django 4.1.6 on 2023-02-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_customer_mobile"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="mobile",),
    ]
