# Generated by Django 4.1.6 on 2023-02-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_order_change_address_updateaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="updateaddress",
            name="username",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
