# Generated by Django 4.1.6 on 2023-02-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_updateaddress_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash On delivery", "Cash On delivery"),
                    ("razorpay", "razorpay"),
                ],
                default=True,
                max_length=20,
            ),
        ),
    ]
