# Generated by Django 4.1.6 on 2023-02-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_order_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart", name="paid", field=models.BooleanField(default=False),
        ),
    ]
