# Generated by Django 4.1.6 on 2023-02-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_cart_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="o_id",
            field=models.CharField(default=True, max_length=200),
        ),
    ]
