# Generated by Django 4.1.6 on 2023-02-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_order_o_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="paid",),
    ]
