# Generated by Django 4.1.6 on 2023-02-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_remove_cart_paid"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="o_id",),
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.customer",
            ),
        ),
    ]
