# Generated by Django 4.1.6 on 2023-02-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_remove_order_o_id_alter_cart_customer"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="razor_pay_order_id",),
        migrations.RemoveField(model_name="cart", name="razor_pay_payment_id",),
        migrations.RemoveField(model_name="cart", name="razor_pay_payment_signature",),
    ]
