# Generated by Django 4.1.6 on 2023-02-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_remove_cart_razor_pay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(default=True, max_length=200),
        ),
    ]
