# Generated by Django 4.1.6 on 2023-02-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_order_order_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="order_id",),
        migrations.AddField(
            model_name="order",
            name="o_id",
            field=models.CharField(default=True, max_length=200),
        ),
    ]
