# Generated by Django 4.1.6 on 2023-02-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_remove_order_order_id_order_o_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="o_id",),
    ]
