# Generated by Django 4.1.6 on 2023-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_remove_order_o_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="discount",),
        migrations.RemoveField(model_name="order", name="new_address",),
        migrations.AddField(
            model_name="order", name="paid", field=models.BooleanField(default=False),
        ),
    ]
