# Generated by Django 4.1.6 on 2023-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_remove_order_discount_remove_order_new_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
